{ config, pkgs, inputs, ... }:
# let
#   home-manager = builtins.fetchTarball "https://github.com/nix-community/home-manager/archive/release-23.05.tar.gz";
# in
{
  imports =
    [ # Include the results of the hardware scan.
      ./hardware-configuration.nix
      inputs.xremap-flake.nixosModules.default
      ../../nixosModules
      ../../users/ginner  # User-specific NixOS config
    ];

  # Use the systemd-boot EFI boot loader.


  networking.hostName = "BISHOP"; # Define your hostname.

  userGlobals = {
    username = "ginner";
  };

  myModules.laptop.enable = true; # Enable laptop bundle

  # sops-nix: use the host SSH ed25519 key for system-level secret decryption.
  # This is generated by OpenSSH on first boot, so no manual key creation is
  # needed at the NixOS level — decryption is automatic on nixos-rebuild switch.
  sops.age.sshKeyPaths = [ "/etc/ssh/ssh_host_ed25519_key" ];

  ## Below has to be handled during the restructure

  home-manager = {
    extraSpecialArgs = { inherit inputs; username = config.userGlobals.username; };
    users = {
      ${config.userGlobals.username} = import ./home.nix;
    };
  };

  myModules.shared.stylix = {
    enable = true;
    image = ../../assets/wall.jpeg;
  };

  myModules.services.tailscale.enable = true;

  # List packages installed in system profile. To search, run:
  # $ nix search wget
  environment.systemPackages = with pkgs; [
    home-manager
  ];

  nix.nixPath = [ "nixpkgs=${inputs.nixpkgs}" ];

  # Some programs need SUID wrappers, can be configured further or are
  # started in user sessions.
  # programs.mtr.enable = true;
  # programs.gnupg.agent = {
  #   enable = true;
  #   enableSSHSupport = true;
  # };

  # List services that you want to enable:

  # Enable the OpenSSH daemon.
  # services.openssh.enable = true;

  # boot.kernelParams = [ 
  #   "usbcore.autosuspend=-1"
  #   "usbcore.use_both_schemes=1"
  # ];
  #

  # Copy the NixOS configuration file and link it from the resulting system
  # (/run/current-system/configuration.nix). This is useful in case you
  # accidentally delete configuration.nix.
  # system.copySystemConfiguration = true;

  # This value determines the NixOS release from which the default
  # settings for stateful data, like file locations and database versions
  # on your system were taken. It's perfectly fine and recommended to leave
  # this value at the release version of the first install of this system.
  # Before changing this value read the documentation for this option
  # (e.g. man configuration.nix or on https://nixos.org/nixos/options.html).
  system.stateVersion = "24.11"; # Did you read the comment?
}

